<?php

define('UUID_ENTITY_FEATURES_REBUILD_CREATE_ONLY', 0);
define('UUID_ENTITY_FEATURES_REBUILD_UPDATE_NON_EMPTY', 1);
define('UUID_ENTITY_FEATURES_REBUILD_UPDATE', 2);
define('UUID_ENTITY_FEATURES_REBUILD_REPLACE', 3);

/**
 * Implements hook_menu().
 */
function uuid_entity_features_menu() {
  $items['admin/config/content/uuid_entity_features'] = array(
    'access arguments' => array('administer site configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('uuid_entity_features_settings_form'),
    'title' => 'UUID entities Features settings',
    'description' => 'Configure the settings for UUID Entity Features Integration.',
  );
  return $items;
}

/**
 * Implements hook_features_api().
 */
function uuid_entity_features_features_api() {
  $components = array();
  //TODO: refactor, array_intersect etc
  $entity_info = entity_get_info();
  $entities_settings = uuid_entity_features_entities_settings();
  foreach($entities_settings as $type => $settings) {
    if(
      !empty($settings['enabled']) &&
      _uuid_entity_features_compatible_entity_type($entity_info[$type])
    ) {
      $components['uuid_entity_' . $type] = array(
        'name' => t('@label entity', array('@label' => $entity_info[$type]['label'])),
        'feature_source' => TRUE,
        'default_hook' => 'uuid_entity_default_' . $type,
        'default_file' => FEATURES_DEFAULTS_INCLUDED,
        'file' => drupal_get_path('module', 'uuid_entity_features') . '/includes/uuid_entity.features.inc',
        'base' => 'uuid_entity',
        //TODO: Provide hook to set weight depending entity type?
        //Rebuild menu_links last since otherwise might link
        //to not yet rebuilt (locally stored) entities
        'weight' => $type === 'menu_link' ? 10 : 0,
      );
    }
  }
  return $components;
}

function _uuid_entity_feature_component($component_name) {
  return strpos($component_name, 'uuid_entity_') === 0;
}

function uuid_entity_features_uuid_entity_features_export_render_node_entity_alter($node, $context) {
  unset($node->translations);
  unset($node->entity_translation_handler_id);
  unset($node->rdf_mapping);
  unset($node->created);
  unset($node->changed);
  unset($node->log);
  unset($node->revision_timestamp);
  unset($node->title_original);
  unset($node->last_comment_timestamp);
}

function uuid_entity_features_uuid_entity_features_node_export_alter(&$export, &$pipe, $context) {
  static $processed_node_uuids = array();
  $node_uuids = array_diff($context['data'], $processed_node_uuids);
  if(!empty($node_uuids)) {
    $settings = uuid_entity_features_entities_settings();
    $ids = entity_get_id_by_uuid('node', $node_uuids);
    $nodes = entity_load('node', $ids);
    if(module_exists('entity_menu_links') && FALSE) {
      foreach($nodes as $node) {
        //Clone node object so that menu object will not
        //be included in export, or committed to entity cache
        $node = clone $node;
        menu_node_prepare($node);
        //Or collect mlids and load multiple?
        if(!empty($node->menu['mlid'])) {
          $mlids = _uuid_entity_features_menu_link_plids($node->menu);
          $uuids = entity_get_uuid_by_id('menu_link', $mlids);
          $menu_links = entity_uuid_load('menu_link', $uuids);
          foreach($menu_links as $mlid => $menu_link) {
            $pipe['uuid_entity_menu_link'][$menu_link->uuid] = $menu_link->uuid;
            if(!isset($menu_link->mlid)) {
              //entity_menu_links_linked_entity will try to access mlid
              //set to null so PHP doesn't complain
              $menu_link->mlid = NULL;
            }
            $linked_entity = entity_menu_links_linked_entity($menu_link, TRUE);
            if(!empty($linked_entity) && $settings[$linked_entity['type']]['enabled']) {
              if($mlid != $node->menu['mlid']) {
                $pipe["uuid_entity_{$linked_entity['type']}"][$linked_entity['uuid']] = $linked_entity['uuid'];
                if($linked_entity['type'] === 'node') {
                  $processed_node_uuids[] = $linked_entity['uuid'];
                }
              }
            }
          }
        }
      }
    }
  }
}

function _uuid_entity_features_menu_link_entity($menu_link) {
  if(!isset($menu_link->mlid)) {
    //entity_menu_links_linked_entity will try to access mlid
    //set to null so PHP doesn't complain
    $menu_link->mlid = NULL;
  }
  return entity_menu_links_linked_entity($menu_link, TRUE);
}

//Option to exclude self?
function _uuid_entity_features_menu_link_plids($menu_link) {
  $mlids = array();
  $menu_link = (object) $menu_link;
  foreach(range(1, MENU_MAX_DEPTH) as $n) {
    if(empty($menu_link->{"p$n"})) {
      break;
    }
    $mlids[] = $menu_link->{"p$n"};
  }
  return $mlids;
}

function uuid_entity_features_uuid_entity_features_menu_link_export_alter(&$export, &$pipe, $context) {
  $menu_links = entity_uuid_load('menu_link', $context['data']);
  $settings = uuid_entity_features_entities_settings();
  foreach($menu_links as $menu_link) {
    $linked_entity = _uuid_entity_features_menu_link_entity($menu_link);
    if(!empty($linked_entity) && $settings[$linked_entity['type']]['enabled']) {
      $pipe["uuid_entity_{$linked_entity['type']}"][$linked_entity['uuid']] = $linked_entity['uuid'];
    }
    foreach(_uuid_entity_features_menu_link_plids($menu_link) as $menu_link_uuid) {
      $pipe['uuid_entity_menu_link'][$menu_link_uuid] = $menu_link_uuid;
    }
  }
}

function uuid_entity_features_uuid_entity_features_export_render_menu_link_entity_alter($menu_link, $context) {
  unset($menu_link->timestamp);
  unset($menu_link->i18n_tsid);
  unset($menu_link->rdf_mapping);
  unset($menu_link->localized_options);
  unset($menu_link->href);
  $schema = drupal_get_schema('menu_router');
  foreach(array_keys($schema['fields']) as $router_property) {
    unset($menu_link->{$router_property});
  }
}

/**
 * Implements hook_uuid_entity_default_menu_link_alter()
 */
/*
function uuid_entity_features_uuid_entity_default_menu_link_alter(&$menu_links) {
}
 */
function uuid_entity_features_uuid_entity_features_rebuild_menu_link_entities_alter(&$menu_links, $context) {
  $entities_by_type = array();
  $entities_menu_links = array();
  foreach($menu_links as $uuid => $menu_link) {
    $linked_entity = entity_menu_links_linked_entity($menu_link, TRUE);
    if(!empty($linked_entity)) {
      $entities_menu_links[$linked_entity['uuid']][] = $uuid;
      $entities_by_type[$linked_entity['type']][] = $linked_entity['uuid'];
    }
  }
  $missing_uuids = array();
  foreach($entities_by_type as $type => $uuids) {
    $ids = entity_get_id_by_uuid($type, $uuids);
    $missing_uuids = array_diff($uuids, array_flip($ids));
  }
  foreach($missing_uuids as $uuid) {
    foreach($entities_menu_links[$uuid] as $menu_link_uuid) {
      //TODO: also print module, component etc?
      $menu_link_wrapper = entity_metadata_wrapper('menu_link', $menu_links[$menu_link_uuid]);
      drupal_set_message(
        t(
          'Menu link "@label" (uuid: @uuid) could not be rebuilt because the linked entity (uuid: @entity_uuid) is missing.',
          array(
            '@label' => $menu_link_wrapper->label(),
            '@uuid' => $menu_link_uuid,
            '@entity_uuid' => $uuid,
          )
        ),
        'warning'
      );
      unset($menu_links[$menu_link_uuid]);
    }
  }
}

function uuid_entity_features_init() {
  //uuid_entity_features_entities_entity_info();
}

function uuid_entity_features_entities_entity_info() {
  return array_filter(entity_get_info(), '_uuid_entity_features_compatible_entity_type');
}

//TODO: refactor?
function _uuid_entity_features_compatible_entity_type($info) {
  return isset($info['uuid']) && $info['uuid'] && empty($info['exportable']);
}

function _uuid_entity_features_component_entity_type($component) {
  return substr($component, strlen('uuid_entity_'));
}

function uuid_entity_features_entities_settings() {
  $entities_settings = variable_get('uuid_entity_features_entities', array());
  foreach(uuid_entity_features_entities_entity_info() as $type => $info) {
    $entities_settings[$type] =
      (isset($entities_settings[$type]) ? $entities_settings[$type] : array()) + array(
        'enabled' => FALSE,
        'bundles' => array(),
        'rebuild_behavior' => UUID_ENTITY_FEATURES_REBUILD_CREATE_ONLY,
        //'properties' = module_invoke_all('uuid_entity_features_entity_excluded_prop
      );
  }
  return $entities_settings;
}

/*
define('UUID_ENTITY_FEATURES_ENTITY_PROPERTY_OBJECT', 0);
define('UUID_ENTITY_FEATURES_ENTITY_PROPERTY_METADATA_WRAPPER', 0);
function uuid_entity_features_export_entity_object_properties_exclude($entity_type) {
  if($entity_type === 'node') {
    return array(
      'translations',
      'entity_translation_handler_id',
      'rdf_mapping',
      'created',
      'changed',
      'log',
      'revision_timestamp',
      'title_original',
      'last_comment_timestamp',
    );
  }
}
*/

/**
 * Menu callback to configure module settings.
 */
function uuid_entity_features_settings_form($form, &$form_state) {
  $entities_settings = uuid_entity_features_entities_settings();

  $form['uuid_entity_features_entities'] = array(
    '#tree' => TRUE,
  );

  //TODO: view filter
  foreach (uuid_entity_features_entities_entity_info() as $type => $info) {
    if(isset($info['uuid']) && $info['uuid']) {
      $bundle_options = array();
      if(
        !empty($info['entity keys']['bundle']) &&
        !empty($info['bundles'])
      ) {
        foreach($info['bundles'] as $bundle => $bundle_info) {
          $bundle_options[$bundle] = $bundle_info['label'];
        }
      }
      $settings = $entities_settings[$type];
      $form['uuid_entity_features_entities'][$type] = array(
        '#title' => drupal_strtolower(str_replace(' ', '_', $info['label'])) === drupal_strtolower($type) ?
          $info['label'] :
          t('@label (@type)', array('@label' => $info['label'], '@type' => $type)),
        '#type' => 'fieldset',
        '#collapsible' => TRUE,
        '#collapsed' => TRUE,
        '#description' => NULL, //TODO
        '#tree' => TRUE,
      );
      $form['uuid_entity_features_entities'][$type]['enabled'] = array(
        '#title' => t('Enable features component'), //Make exportable in features? Better title
        '#type' => 'checkbox',
        '#descritpion' => NULL, //TODO
        '#default_value' => $settings['enabled'],
      );
      if(!empty($bundle_options)) {
        $form['uuid_entity_features_entities'][$type]['bundles'] = array(
          '#type' => 'checkboxes',
          '#title' => t('Exportable @label bundles', array('@label' => drupal_strtolower($info['label']))),
          '#default_value' => $settings['bundles'],
          '#options' => $bundle_options,
        );
      }
      $form['uuid_entity_features_entities'][$type]['rebuild_behavior'] = array(
        '#type' => 'radios',
        '#title' => t('Rebuild behavior'),
        '#description' => NULL, //TODO Not abour how
        // different settings will effect "overriden" status etc
        '#options' => array(
          UUID_ENTITY_FEATURES_REBUILD_CREATE_ONLY => t('Create non existing entities only'),
          UUID_ENTITY_FEATURES_REBUILD_UPDATE_NON_EMPTY => t('Update existing entities, excluding empty properties on exported entities'),
          UUID_ENTITY_FEATURES_REBUILD_UPDATE => t('Update exising entites'),
          UUID_ENTITY_FEATURES_REBUILD_REPLACE => t('Replace existing entities'),
        ),
        '#default_value' => $settings['rebuild_behavior'],
      );
      /*
      $form['uuid_entity_features_entities'][$type]['properties'] = array(
        '#type' => 'fieldset',
        '#title' => t('Properties'),
        '#description' => NULL, //TODO:
        '#collapsible' => TRUE,
        '#collapsed' => TRUE,
      );
      */
      //entity_get_property_info($type));
      //entity_get_all_property_info
      /*
      foreach(entity_get_property_info($type) as $property => $property_info) {
      }
      */
    }
  }

  //TODO: empty features cache if new enabled!
  return system_settings_form($form);
}

function uuid_entity_features_settings_form_validate($form, &$form_state) {
  foreach($form_state['values']['uuid_entity_features_entities'] as $type => &$settings) {
    $settings['bundles'] = array_filter($settings['bundles']);
  }
}
